name: WebView
on: [push]
jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Download dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-dev
        make dep

    - name: Build
      run: |
        make linux

    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: discord-bot-gui_linux
        path: bin/discord-bot-gui_linux
    
    - name: Run Tests
      run: |
        make dep test
  
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Download dependencies
      run: |
        make dep dep-darwin

    - name: Build
      run: |
        make darwin

    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: discord-bot-gui_darwin
        path: 'bin/discord-bot-gui_darwin-app'

    - name: Run Tests
      run: |
        make dep test
  
  buid-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Download dependencies
      run: |
        make dep

    - name: Build
      run: |
        make win

    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: discord-bot-gui_win64.exe
        path: bin/discord-bot-gui_win64.exe

    - name: Run Tests
      run: |
        make dep test